title: wtrace.net
author: © wtrace.net 2024
email: contact@wtrace.net
description: >- # this means to ignore newlines until "baseurl:"
  Tools and materials for software and system troubleshooting 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wtrace.net" # the base hostname & protocol for your site, e.g. http://example.com

youtube_username: "@lowleveldesign"
github_username:  lowleveldesign

permalink: pretty

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

header_pages:
  - guides.md
  - tools.md
  - about.md
